package luafilters

import (
	"time"
)

// FilterType represents the type of filter (input or output)
type FilterType string

const (
	// FilterTypeInput represents an input filter that processes parameters before execution
	FilterTypeInput FilterType = "input"

	// FilterTypeOutput represents an output filter that processes results after execution
	FilterTypeOutput FilterType = "output"
)

// HookContext contains the context information passed to Lua filter functions
// This structure is converted to a Lua table and passed to filter functions
type HookContext struct {
	// ServerName is the name of the downstream MCP server
	ServerName string `json:"server_name"`

	// ToolName is the name of the tool being executed
	ToolName string `json:"tool_name"`

	// Parameters contains the input parameters (for input filters)
	// or nil (for output filters)
	Parameters map[string]interface{} `json:"parameters,omitempty"`

	// Result contains the execution result (for output filters)
	// or nil (for input filters)
	Result map[string]interface{} `json:"result,omitempty"`

	// RequestID is a unique identifier for this request
	RequestID string `json:"request_id"`

	// Timestamp is when the hook was triggered
	Timestamp int64 `json:"timestamp"`

	// Duration is the execution time in milliseconds (for output filters only)
	Duration int64 `json:"duration,omitempty"`

	// FilterType indicates whether this is an input or output filter
	FilterType FilterType `json:"filter_type"`
}

// HookResult represents the result of applying a filter
type HookResult struct {
	// Modified indicates whether the filter made any changes
	Modified bool

	// Data contains the filtered data (parameters or result)
	Data map[string]interface{}

	// Error contains any error that occurred during filter execution
	Error error

	// ErrorMessage contains a human-readable error message
	ErrorMessage string

	// ExecutionTime is how long the filter took to execute
	ExecutionTime time.Duration

	// Logs contains any log messages generated by the filter
	Logs []string
}

// FilterFunc represents a filter function interface
type FilterFunc func(context *HookContext) (*HookResult, error)

// FilterConfig holds configuration for a specific filter
type FilterConfig struct {
	// Enabled indicates whether this filter is active
	Enabled bool

	// ServerName is the name of the server this filter applies to
	// Empty string means it applies to all servers (global filter)
	ServerName string

	// FilterType indicates whether this is an input or output filter
	FilterType FilterType

	// FunctionName is the Lua function name to call
	FunctionName string

	// Timeout is the maximum execution time for this filter
	Timeout time.Duration

	// StrictMode determines behavior on filter errors
	// If true, errors abort the operation
	// If false, errors are logged but operation continues with original data
	StrictMode bool
}

// NewInputContext creates a new HookContext for an input filter
func NewInputContext(serverName, toolName string, parameters map[string]interface{}, requestID string) *HookContext {
	return &HookContext{
		ServerName: serverName,
		ToolName:   toolName,
		Parameters: parameters,
		RequestID:  requestID,
		Timestamp:  time.Now().Unix(),
		FilterType: FilterTypeInput,
	}
}

// NewOutputContext creates a new HookContext for an output filter
func NewOutputContext(serverName, toolName string, result map[string]interface{}, requestID string, duration time.Duration) *HookContext {
	return &HookContext{
		ServerName: serverName,
		ToolName:   toolName,
		Result:     result,
		RequestID:  requestID,
		Timestamp:  time.Now().Unix(),
		Duration:   duration.Milliseconds(),
		FilterType: FilterTypeOutput,
	}
}

// NewHookResult creates a new HookResult with default values
func NewHookResult() *HookResult {
	return &HookResult{
		Modified: false,
		Data:     make(map[string]interface{}),
		Logs:     make([]string, 0),
	}
}

// IsSuccess returns true if the filter executed without errors
func (hr *HookResult) IsSuccess() bool {
	return hr.Error == nil
}

// SetError sets an error on the HookResult
func (hr *HookResult) SetError(err error, message string) {
	hr.Error = err
	hr.ErrorMessage = message
}

// AddLog adds a log message to the HookResult
func (hr *HookResult) AddLog(message string) {
	hr.Logs = append(hr.Logs, message)
}
